---
name: Check for updates to default blocklist

on:
  schedule:
    - cron: '23 10 * * 1-5'

  workflow_dispatch: # enables "click to run" button

env:
  ELIXIR_VERSION: 1.15

jobs:
  blocklist_update:
    name: Check for updates to the default blocklist
    runs-on: ubuntu-latest
    steps:
      - id: elixir-version-to-otp-version
        name: "Read %{Elixir version => OTP version} map"
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.github/workflows/elixir_version_to_otp_version.json

      - id: setup-beam
        name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          # otp-version: https://stackoverflow.com/a/64405821
          otp-version: |
            ${{ fromJson(steps.elixir-version-to-otp-version.outputs.content)[env.ELIXIR_VERSION] }}
          elixir-version: ${{env.ELIXIR_VERSION}}
        env:
          GITHUB_TOKEN: ${{github.token}}

      - run: |
          .github/workflows/default-blocklist-updater.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
